### ISSUE TITLE
Delay window came back after updating

### ISSUE THREAD

**Issue by dayzlun** [kytwb/ferdi#11]
**Describe the bug**
Delay window came back after updating via the update prompt after installing on windows with the .exe

 - OS: Windows 10 Pro
 - Browser chrome
 - Version 5.2.0

**Comment by ZeroCool940711** [comment]
Having this exact problem too.

**Comment by sunk818** [comment]
@dayzlun Makes sense that Beta4 is from the franz site and not from here. What are you proposing? No checks on new versions?

**Comment by ZeroCool940711** [comment]
I think it would be nice to have an option to choose if we want to update from the official site or from this repository.

**Comment by dayzlun** [comment]
@sunk818 It was an unremovable message for updating so... What else can I do

**Comment by sunk818** [comment]
@dayzlun Yes, it is unremovable message. After I updated, I had same problem, but I re-installed beta3 from here. I just ignore the banner now. 

@ZeroCool940711 yes, there are many nice things we can have if you know how to code. Hopefully when @kytwb has more time, can have a beta4 release so the update banner below disappears. :)

![image](https://user-images.githubusercontent.com/6989799/61733512-d716a180-ad34-11e9-8af8-9207eed516cb.png)

**Comment by ZeroCool940711** [comment]
Hey @sunk818 and @dayzlun, check the [PR](https://github.com/kytwb/ferdi/pull/13) I made a few minutes ago here on the ferdi repository, I think it should now check for updates on the ferdi repository instead of the franz repo, also there is some info I put in a comment on that PR explaining how to make ferdi stop updating from the franz repo if you have it already installed because you used the installer from the repo.

**Comment by kytwb** [comment]
@ZeroCool940711 PR merged, will see to make a new release or update the existing one soon.

**Comment by kytwb** [comment]
Fixed in latest release: https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.2.1-beta.1

**Comment by kytwb** [comment]
@all-contributors please add dayzlun for bug
