### ISSUE TITLE
More sustainable way to unlock Premium features

### ISSUE THREAD

**Issue by kytwb** [kytwb/ferdi#15]
Would be nice to make every user premium by default (see `isPremium`): https://github.com/kytwb/ferdi/blob/f927ed93fa0b3195edd017ccef2b761e508b8247/src/models/User.js#L23
More sustainable way to achieve the current goal.

**Comment by ArviTheMan** [comment]
So the point of this is not to ask everyone money but to enable all features by default? Reading about [the issue with leftover Franz nonsense](https://github.com/getferdi/ferdi/issues/1040), I thought you wanted to get everyone to pay you and I was worried for a bit.

**Comment by vantezzen** [comment]
> I thought you wanted to get everyone to pay you and I was worried for a bit

The reason we started Ferdi is because Franz started wanting everyone to pay. We removed all those annoying paywalls and added many awesome free features.

Ferdi is and will always be free and without the need to pay for any features. We finance Ferdi's development and server costs on the many people that donate through our OpenCollective (https://opencollective.com/getferdi) and our sponsors DigitalOcean and Parallels
