### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by igreil** [kytwb/ferdi#2]
The fork and modification of "Franz" is much appreciated, but the name should probably be changed as well. 

I propose "Ferdl", which is short for Ferdinand. (Ferdinand I was the successor of Francis (Franz) II as emperor of Austria.) Keeping both the first letter as well as the overall number of letters should help adoption and recognition.

**Comment by marcolopes** [comment]
Also, a logo change would be nice! The original logo is really ugly.

**Comment by kytwb** [comment]
Sure, I will see to change the name shortly.

**Comment by kytwb** [comment]
I've renamed the repository and changed the SVG logo available in the repository (using dark background instead of the blue gradient). I'll have to see to replace all occurrences of Franz to Ferdi and apply the logo changes to the different PNGs all over the repository (different sizes, format, etc.). I haven't seen a script to generate those assets automatically in the repository.

**Comment by bittner** [comment]
:heart: the name Ferdi. :smile:

**Comment by bittner** [comment]
Not a technical issue, but for sake of historical correctness:

> Ferdinand I was the successor of Francis (Franz) II as emperor of Austria.

I think it was the other way round. [Franz Josef I](https://en.wikipedia.org/wiki/Franz_Joseph_I_of_Austria) was the successor of [Ferdinand I](https://en.wikipedia.org/wiki/Ferdinand_I_of_Austria).

Yet still, I like the name Ferdinand a lot. It's a very soft-sounding name. "Ferdi" or "Ferdl" alike. Good choice! :+1:

**Comment by igreil** [comment]
Francis **Joseph**, sure. But Ferdinand I _was_ the successor of Francis I.
[https://en.wikipedia.org/wiki/Emperor_of_Austria#Emperors_of_Austria_(1804%E2%80%931918)](url)

**Comment by bittner** [comment]
Sure, that's where the confusion comes from (or, at least, my confusion): Franz, the application, is about emperor Franz Joseph. The logo is his well-known beard.

**Comment by bittner** [comment]
I see that the [releases](https://github.com/kytwb/ferdi/releases) are packaged as "Franz" for all, the then-installed Debian package, the Desktop shortcut and the content of the About box. There is no way (at least no easy or obvious one) to verify that what is installed is actually "Ferdi", and not "Franz".

Franz Ferdinand
-----------
It might be fine to keep the binary name, the package name, the desktop shortcut file name, etc. the same. But could we maybe slightly adapt the following?

- the name in the About box _Menu > Window > About Franz_ (`Franz` -> `Franz Ferdinand`)
- the Name in _/usr/share/applications/franz.desktop_ (`Name=Franz` -> `Name=Franz Ferdinand`)

If I knew where to find the related code pieces -- I admit, I'm really struggling with that -- I'd prepare a PR. The "right" place for the customization is probably the packaging process in the pipeline (not the original code). Not sure, though. Any hints?

Fine-print
-----
_I love the idea to keep the connection to the original "Franz" by using "Franz Ferdinand" (instead of just "Ferdi") for the customizations. This may also help to avoid shocking strongly attached Franz users. And it's a nice historic link to the member of the royal family whose assassination marked the beginning of World War I, a dramatic event with outreach to even today._

**Comment by kytwb** [comment]
@bittner thanks for the contribution! I don't have a hard feeling on the naming; whatever works. Regarding the implementation, will have to see to rename only in strategic places as you mentionned. I'm very busy with @guardrailsio at the moment, but I will take a look asap if nobody comes up with a pull request 🙏

**Comment by bittner** [comment]
The 5.3.0 release is awesome! THANK YOU!

The coloring is different now, and so is the logo. However, the name in the About box has remained as it was:

![Franz-Ferdinand-About-box](https://user-images.githubusercontent.com/665072/64465844-04fe4c80-d10f-11e9-8366-ad2f042ccb8a.png)

Can we set
1. the About box _title_ to "Ferdi" (`Franz` -> `Ferdi`), and
1. the _header_ of the About box text to "Franz Ferdinand"? (`Franz` -> `Franz Ferdinand`)

The could be funny, in a way. It's "Ferdi", but "Franz" and "Ferdinand" is the link between them.

I can provide the change (PR) myself, but please point out which parts of the code to change as I'm missing the practice a bit. :grimacing:

**Comment by kytwb** [comment]
@all-contributors please add @igreil and @marcolopes for ideas

**Comment by kytwb** [comment]
@all-contributors please add @marcolopes for ideas

**Comment by kytwb** [comment]
@all-contributors please add @marcolopes for ideas

**Comment by kytwb** [comment]
@all-contributors please add @marcolopes for ideas

Sorry for the spam; will add credits as we go now with the bot.

**Comment by kytwb** [comment]
@all-contributors please add @marcolopes for ideas

**Comment by kytwb** [comment]
Sorry for the spam; will add credits as we go now with the bot.
